
# =================================================================
# LOKI - CONFIGURAÇÃO PARA LOGS CENTRALIZADOS
# =================================================================

# Desabilita autenticação para ambiente de desenvolvimento
auth_enabled: false

# Configurações do servidor
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

# Configurações comuns para todos os componentes
common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Configuração do ingester (responsável por receber e processar logs)
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

# Configuração do schema (como os dados são organizados)
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Configuração de armazenamento
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

# Configuração de compactação
compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem

# Configuração de limites
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_concurrent_tail_requests: 20
  max_query_parallelism: 32

# Configuração de cache para consultas
chunk_store_config:
  max_look_back_period: 0s

# Configuração de consultas com range
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 1h

# Configuração do distributor (entrada de dados)
distributor:
  ring:
    kvstore:
      store: inmemory

# Configuração do querier (consultas)
querier:
  query_ingesters_within: 3h

# Configuração de retenção de dados
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# Configuração do ruler (regras e alertas)
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

# Configuração de métricas internas
analytics:
  reporting_enabled: false