{
 "title": "Weather Metrics",
 "tags": [
  "weather",
  "business"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Taxa de Requisições de Previsão do Tempo",
   "type": "timeseries",
   "description": "Taxa de requisições para previsões do tempo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(weather_forecast_requests_total[1m])",
     "legendFormat": "Requisições por segundo"
    }
   ]
  },
  {
   "title": "Distribuição de Temperaturas",
   "type": "bargauge",
   "description": "Distribuição de temperaturas previstas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_forecast_temperature_celsius_bucket",
     "legendFormat": "{{le}}°C"
    }
   ]
  },
  {
   "title": "Distribuição de Condições Climáticas",
   "type": "piechart",
   "description": "Contagem de previsões por resumo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(summary) (weather_forecast_summary_total)",
     "legendFormat": "{{summary}}"
    }
   ]
  },
  {
   "title": "Mapa de Serviço",
   "type": "servicemap",
   "description": "Mapa de serviço mostrando fluxo de requisições",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{span_kind=\"server\"}",
     "serviceName": "observability-webapi"
    }
   ]
  },
  {
   "title": "Temperatura Média por Dia",
   "type": "heatmap",
   "description": "Média de temperatura por dia",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(day) (weather_forecast_temperature_celsius_sum / weather_forecast_temperature_celsius_count)",
     "legendFormat": "Dia {{day}}"
    }
   ]
  }
 ]
}